name: Check Symbol

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - requested

jobs:
  check-symbol:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: WonyoungChoi/PrivateData
        token: ${{ secrets.MY_PAT }}

    - name: Examin Environment
      run: |
        ls -al
        env

    - name: Test Script
      uses: actions/github-script@v4
      with:
        script: |
          console.log(JSON.stringify(context.payload))
