name: Build Docker

on:
  push:
    branches:
      - 'docker-test'
    # branches:
    #   - 'flutter-*'
    # paths:
    #   - 'ci/docker/tizen/**'
    #   - 'DEPS'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ci/docker/tizen
        file: ci/docker/tizen/Dockerfile
        push: true
        tags: |
          ghcr.io/wonyoungchoi/build-engine:latest

