name: Build Docker

on:
  push:
    branches:
      - "flutter-*-tizen"
    paths:
      - "ci/tizen/docker/**"
      - "DEPS"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ci/tizen/docker
          file: ci/tizen/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/build-engine:latest
