name: Build Docker

on:
  push:
    branches:
      - 'flutter-*'
    paths:
      - 'ci/docker/tizen/**'
      - 'DEPS'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      id: branch
      run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/})"

    - uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ci/docker/tizen
        file: ci/docker/tizen/Dockerfile
        push: true
        build-args:
          GIT_BRANCH=${{ steps.branch.outputs.name }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/build-engine:latest
